### ISSUE TITLE
Silky doesn't work when django.middleware.gzip.GZipMiddleware is enabled

### ISSUE THREAD

**Issue by melbic** [mtford90/silk#43]
When the  'django.middleware.gzip.GZipMiddleware' is enabled the following error happens:
  File "...r/lib/python2.7/site-packages/silk/sql.py", line 39, in execute_sql
    sql_query = q % params
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)

**Comment by mtford90** [comment]
Closing this as can be solved by middleware placement. Let me know if you're still havin issues tho @melbic
