### ISSUE TITLE
UTC time in templates

### ISSUE THREAD

**Issue by pix666** [mtford90/silk#49]
Maybe should add "expects_localtime=True" to filter silk_date_time?

```
# templatetags/filters.py

@register.filter(expects_localtime=True)
def silk_date_time(dt):
    return _silk_date_time(dt)
```

**Comment by mtford90** [comment]
Not familiar with this - what does it do? Just translates into local time?

**Comment by pix666** [comment]
Yes, it is:
https://docs.djangoproject.com/en/1.7/howto/custom-template-tags/#filters-and-time-zones

**Comment by mtford90** [comment]
Great, will add this in the next update also.

**Comment by mtford90** [comment]
Done
