### ISSUE TITLE
'thread._local' object has no attribute 'temp_identifier' (should log a warning stating that this is likely a middleware issue)

### ISSUE THREAD

**Issue by darxsys** [mtford90/silk#52]
I've just installed silk and configured it as it says on your tutorial. However, as soon as I enable the middleware, my site breaks with this error inside the get_identifier method of DataCollector class. Why would this happen? As soon as I disable silk middleware, the site works again. Also, I had to add a logger handler for silk before that since it was throwing an error because of that too. This tool looks promising, I hope you can fix this asap.

**Comment by mtford90** [comment]
Hey @darxsys sorry you're having issues.

This sounds like a middleware ordering issue. If Silk is placed after a piece of middleware that does not return from `process_request`/`process_response` it will break.

**Comment by darxsys** [comment]
Thank you for your response. Yes, it definitely is some kind of an issue with the middleware ordering in both directions. What I've noticed is that, depending on where I position silk middleware, it throws two different errors. The first one is the one I've originally posted and the second one says something like:

`No request model found while processing response. `

I guess the system returns from both `process_request` and `process_response` somewhere.

**Comment by mtford90** [comment]
@darxsys yeah it's a real pain getting the ordering correct, I wish there was a way of intercepting requests/responses without being part of the middleware stack (perhaps there is?), in which case this would no longer be an issue.

In the meantime i think it will be a good idea to at least catch this error and log a warning stating that middleware placement is likely the issue. I'll leave this issue open to track that.

I will create a seperate issue to track the logging bug - although I haven't been able to replicate that myself

**Comment by darxsys** [comment]
I've delved a little deeper into the middleware of our system and it seems that some of them return from process request/response. I'll try reordering them a bit if that is even possible. I wish there was such a way too, don't know about it though. Thanks for help!

**Comment by mtford90** [comment]
An error is now raised in incorrect middleware order is corrected rather than the `temp_identifier` error

**Comment by kqr** [comment]
@mtford90 The error raised says

> Ordering must ensure that Silk middleware can execute process_request and process_response. If an earlier middleware returns from either of these methods, Silk will not have the chance to inspect the request/response objects.

What confuses me about this message is that process_response context handlers *are supposed* to return a HttpResponse, so unless Silk is at the bottom of the stack (which might not be wanted) an earlier response middleware will return.

> process_response() is called on all responses before they’re returned to the browser. […] It must return an HttpResponse or StreamingHttpResponse object. It could alter the given response, or it could create and return a brand-new HttpResponse or StreamingHttpResponse.

What you probably mean though is that

> In particular, this means that your process_response() method cannot rely on setup done in process_request().

which means both ends of Silk needs process_request to be triggered, so anything higher in the stack there can't return. This is correct in the readme file, but the error message is confusing.

Might be something to think about.
