### ISSUE TITLE
Should not have to manually add a logger for silk

### ISSUE THREAD

**Issue by mtford90** [mtford90/silk#53]
As reported by @darxsys in #52

**Comment by mtford90** [comment]
@darxsys, i haven't been able to replicate this... even if I delete the silk logger from `LOGGING` in my `settings.py`, i do not get an error. Can you remember what error was being thrown? Also what django/python version?

**Comment by darxsys** [comment]
Sorry for being slow. I am using django 1.5.5 with python 2.7.3. Not sure about the errors anymore though.

**Comment by mtford90** [comment]
Ok yeah this seems to be a django 1.5 error. Django 1.5 has been deprecated now so I'm not going to make any attempts to support it fully
