### ISSUE TITLE
Pin six.py within silk to avoid version incompatibility.

### ISSUE THREAD

**Issue by softshape** [mtford90/silk#70]
Just installed silk, but after this Django won't start.

  File "C:\Python27\lib\site-packages\silk\urls.py", line 6, in <module> from silk.views.request_detail import RequestView
  File "C:\Python27\lib\site-packages\silk\views\request_detail.py", line 8, in <module> from silk.code_generation.curl import curl_cmd
  File "C:\Python27\lib\site-packages\silk\code_generation\curl.py", line 5, in <module> from six.moves.urllib.parse import urlencode
ImportError: No module named urllib.parse

What is the six module?

**Comment by mtford90** [comment]
Hmm, what version of six do you have installed? Six is used for py2/py3 compatibility.

**Comment by softshape** [comment]
Django 1.8 has \site-packages\django\utils\six.py version 1.9.0

**Comment by mtford90** [comment]
Silk won't use Django's version of six but rather whatever is available within your environment. You can see in `requirements.txt` that I used six 1.6 when developing.

Can you run `pip freeze` in your dev environment and see which version you have?

I suspect I will probably need to copy what Django does and include six.py within the project e.g. silk.utils.six.

**Comment by softshape** [comment]
Found another (old) copy of six.py in "requests" module and updated it to Django's copy. Now it starts OK, but crashes after server request. Log says-

IntegrityError at /
null value in column "view_name" violates not-null constraint
Exception Location:	C:\Python27\lib\site-packages\django\db\backends\utils.py in execute, line 64

**Comment by mtford90** [comment]
Ok, you're now experiencing #66 which is fixed in master but not released yet. I'll pin six.py before making a release but for now you can run:

```
pip install -e git+https://github.com/mtford90/silk.git#egg=silk
```

To use silk master which should fix that `IntegrityError`

**Comment by softshape** [comment]
It's still there, the same error. I also tried to delete silk tables and recreate them with syncdb but it this won't work. Do you know how to create them without syncdb?

**Comment by mtford90** [comment]
Ahhh figured it out, here is the field declaration:

```
view_name = CharField(max_length=300, db_index=True, blank=True, default='', null=True)
```

However the initial migrations were never updated with `null=True`. I have updated this and pushed to master. Please try re-installing from master, drop the tables and execute `syncdb`/`migrate` again. Let me know if it works :)

**Comment by mtford90** [comment]
Okay six is now pinned within master so should be no more six compat issues like this.
